// Shared Open Graph card style (black background, white title, muted
// description, Inter) used by both the per-post route and the site-wide card.
export function ogImageOptions(page: { title: string; description?: string }) {
  return {
    title: page.title,
    description: page.description ?? "",
    logo: {
      path: "./src/assets/icons/icon.png",
      size: [72, 72] as [number, number],
    },
    bgGradient: [
      [10, 10, 10],
      [10, 10, 10],
    ] as [number, number, number][],
    border: {
      color: [38, 38, 38] as [number, number, number],
      width: 2,
      side: "inline-start" as const,
    },
    padding: 64,
    font: {
      title: {
        color: [250, 250, 250] as [number, number, number],
        size: 64,
        weight: "SemiBold" as const,
        lineHeight: 1.2,
        families: ["Inter Variable"],
      },
      description: {
        color: [163, 163, 163] as [number, number, number],
        size: 30,
        lineHeight: 1.4,
        families: ["Inter Variable"],
      },
    },
    // CanvasKit can't read woff2, so OG cards use raw TTF Inter instances
    // (generated by scripts/subset-fonts.ts) same Inter as the site.
    fonts: [
      "./src/assets/fonts/Inter-400.ttf",
      "./src/assets/fonts/Inter-600.ttf",
    ],
  };
}
